package io.javalive.core.state;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Runtime representation of a component's state schema.
 *
 * <p>Each schema is loaded from the JSON files generated by {@code StateSchemaGenerator}
 * at compile time. At runtime, the {@link StateManager} uses schemas to:
 * <ul>
 *   <li>Initialize state with correct default values (no reflection needed)</li>
 *   <li>Validate incoming state patches</li>
 *   <li>Identify global vs session-scoped fields for proper broadcast routing</li>
 *   <li>Enable the DevTools panel to display field metadata</li>
 * </ul>
 *
 * @author JavaLive Team
 * @since 1.0.0
 */
public class StateSchema {

    /** Component name in kebab-case (e.g., "dashboard"). */
    private String componentName;

    /** Fully qualified Java class name. */
    private String javaClass;

    /** All reactive fields defined in this component. */
    private List<FieldSchema> fields = new ArrayList<>();

    // ─────────────────────────────────────────────────────────────────────────
    // Nested: FieldSchema
    // ─────────────────────────────────────────────────────────────────────────

    public static class FieldSchema {
        private String name;
        private String javaType;
        private String vueType;
        private Object defaultValue;
        private String scope = "session";
        private boolean persist = false;
        private String label;

        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

        public String getJavaType() { return javaType; }
        public void setJavaType(String javaType) { this.javaType = javaType; }

        public String getVueType() { return vueType; }
        public void setVueType(String vueType) { this.vueType = vueType; }

        public Object getDefaultValue() { return defaultValue; }
        public void setDefaultValue(Object defaultValue) { this.defaultValue = defaultValue; }

        public String getScope() { return scope; }
        public void setScope(String scope) { this.scope = scope; }

        public boolean isPersist() { return persist; }
        public void setPersist(boolean persist) { this.persist = persist; }

        public String getLabel() { return label; }
        public void setLabel(String label) { this.label = label; }

        /** True if this field is global-scoped (shared across all sessions). */
        public boolean isGlobal() { return "global".equals(scope); }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Methods
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Creates an initial state map with all fields set to their default values.
     * This is used when a new session first mounts a component.
     *
     * @return a mutable map of fieldName → defaultValue
     */
    public Map<String, Object> createInitialState() {
        Map<String, Object> state = new HashMap<>();
        for (FieldSchema field : fields) {
            state.put(field.getName(), field.getDefaultValue());
        }
        return state;
    }

    /**
     * Returns all fields that are global-scoped (shared across sessions).
     */
    public List<FieldSchema> getGlobalFields() {
        return fields.stream().filter(FieldSchema::isGlobal).toList();
    }

    /**
     * Returns all fields that are session-scoped (per-user state).
     */
    public List<FieldSchema> getSessionFields() {
        return fields.stream().filter(f -> !f.isGlobal()).toList();
    }

    /**
     * Returns all fields that should be persisted to the database.
     */
    public List<FieldSchema> getPersistentFields() {
        return fields.stream().filter(FieldSchema::isPersist).toList();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Getters and setters
    // ─────────────────────────────────────────────────────────────────────────

    public String getComponentName() { return componentName; }
    public void setComponentName(String componentName) { this.componentName = componentName; }

    public String getJavaClass() { return javaClass; }
    public void setJavaClass(String javaClass) { this.javaClass = javaClass; }

    public List<FieldSchema> getFields() { return fields; }
    public void setFields(List<FieldSchema> fields) { this.fields = fields; }

    public boolean hasGlobalFields() {
        return fields.stream().anyMatch(FieldSchema::isGlobal);
    }
}
