package io.javalive.processor.generator;

import io.javalive.processor.model.ComponentModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates the Vue Router configuration from all @VuePage components.
 *
 * <p>After all @VuePage components are processed, this generator creates
 * a single JavaScript file that exports the complete router configuration.
 * This eliminates the need to manually maintain a Vue Router routes array.
 *
 * <h3>Generated file:</h3>
 * {@code static/javalive/router.js}
 *
 * <h3>Example output:</h3>
 * <pre>
 * // Auto-generated by JavaLive
 * import { createRouter, createWebHistory } from 'vue-router';
 *
 * const routes = [
 *   {
 *     path: '/dashboard',
 *     name: 'Dashboard',
 *     component: () => import('./components/dashboard.js'),
 *     meta: { requiresAuth: true, layout: 'default' }
 *   },
 *   {
 *     path: '/users',
 *     name: 'UserManagement',
 *     component: () => import('./components/user-management.js'),
 *     meta: { requiresAuth: true, layout: 'default' }
 *   }
 * ];
 *
 * export const router = createRouter({
 *   history: createWebHistory(),
 *   routes
 * });
 * </pre>
 *
 * @author JavaLive Team
 * @since 1.0.0
 */
public class RouterGenerator {

    private final ProcessingEnvironment processingEnv;
    private final List<ComponentModel> pageComponents = new ArrayList<>();

    public RouterGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    /**
     * Registers a page component to be included in the router.
     * Call this for each @VuePage component as it is processed.
     *
     * @param model the component model (must have isPage() == true)
     */
    public void registerPage(ComponentModel model) {
        if (model.isPage()) {
            pageComponents.add(model);
        }
    }

    /**
     * Generates the router.js file with all registered page components.
     * Call this at the end of the processing round.
     */
    public void generateRouter() {
        if (pageComponents.isEmpty()) return;

        try {
            FileObject file = processingEnv.getFiler()
                .createResource(StandardLocation.CLASS_OUTPUT, "",
                    "static/javalive/router.js");

            try (PrintWriter out = new PrintWriter(file.openWriter())) {
                writeRouter(out);
            }
        } catch (IOException e) {
            // Router generation is non-fatal — the app can still work with manual routing
            processingEnv.getMessager().printMessage(
                javax.tools.Diagnostic.Kind.WARNING,
                "JavaLive: Could not generate router.js: " + e.getMessage()
            );
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Private generation methods
    // ─────────────────────────────────────────────────────────────────────────

    private void writeRouter(PrintWriter out) {
        out.println("// ============================================================");
        out.println("// ⚠️  AUTO-GENERATED FILE — DO NOT EDIT MANUALLY");
        out.println("// Generated by JavaLive Annotation Processor");
        out.println("// Contains routes for all @VuePage components");
        out.println("// ============================================================");
        out.println();
        out.println("import { createRouter, createWebHistory } from 'vue-router';");
        out.println();
        out.println("// ── Route definitions ─────────────────────────────────────────");
        out.println("const routes = [");

        for (ComponentModel page : pageComponents) {
            out.println("  {");
            out.println("    path: '" + page.getVuePath() + "',");
            out.println("    name: '" + page.getRouteName() + "',");
            // Lazy-loaded component for code splitting
            out.println("    component: () => import('./components/" + page.getComponentName() + ".js'),");
            out.println("    meta: {");
            out.println("      requiresAuth: " + page.isRequiresAuth() + ",");
            out.println("      layout: '" + (page.getLayoutName() != null ? page.getLayoutName() : "default") + "',");
            if (page.getPageTitle() != null && !page.getPageTitle().isEmpty()) {
                out.println("      title: '" + page.getPageTitle().replace("'", "\\'") + "',");
            }
            out.println("    },");
            out.println("  },");
        }

        out.println("];");
        out.println();
        out.println("// ── Navigation Guards ─────────────────────────────────────────");
        out.println("export const router = createRouter({");
        out.println("  history: createWebHistory(),");
        out.println("  routes,");
        out.println("  scrollBehavior(to, from, savedPosition) {");
        out.println("    if (savedPosition) return savedPosition;");
        out.println("    return { top: 0 };");
        out.println("  }");
        out.println("});");
        out.println();
        out.println("// Auth guard — redirect to /login if route requires auth");
        out.println("router.beforeEach(async (to, from) => {");
        out.println("  if (to.meta.requiresAuth) {");
        out.println("    const isAuthenticated = window.__JAVALIVE_AUTH__ === true;");
        out.println("    if (!isAuthenticated) {");
        out.println("      return { path: '/login', query: { redirect: to.fullPath } };");
        out.println("    }");
        out.println("  }");
        out.println("  // Update page title");
        out.println("  if (to.meta.title) {");
        out.println("    document.title = to.meta.title;");
        out.println("  }");
        out.println("});");
        out.println();
        out.println("export default router;");
    }
}
