package io.javalive.processor.generator;

import io.javalive.processor.model.*;

import javax.annotation.processing.ProcessingEnvironment;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Generates a Spring WebSocket Controller (STOMP message handler) from a ComponentModel.
 *
 * <p>For each @VueComponent class, this generator produces a Java source file
 * that handles:
 * <ul>
 *   <li>Initial state requests ({@code *.init} messages)</li>
 *   <li>Method dispatch messages (one handler per @VueMethod)</li>
 *   <li>State diffing and pushing patches back to the browser</li>
 *   <li>Global state broadcasts (for @Reactive(scope="global") fields)</li>
 * </ul>
 *
 * <p>Generated files are placed in the {@code {package}.generated} sub-package
 * to keep them separate from hand-written code. They are annotated with a
 * clear "do not edit" warning.
 *
 * <h3>Generated class naming:</h3>
 * {@code Dashboard} → {@code DashboardLiveController}
 *
 * @author JavaLive Team
 * @since 1.0.0
 */
public class SpringControllerGenerator {

    private final ProcessingEnvironment processingEnv;

    public SpringControllerGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    /**
     * Generates the Spring Controller Java source file for the given component.
     *
     * @param model the parsed component model
     */
    public void generate(ComponentModel model) {
        String qualifiedName = model.getGeneratedControllerQualifiedName();

        try {
            JavaFileObject file = processingEnv.getFiler().createSourceFile(qualifiedName);
            try (PrintWriter out = new PrintWriter(file.openWriter())) {
                writeController(out, model);
            }
        } catch (IOException e) {
            throw new RuntimeException(
                "JavaLive: Failed to generate Spring Controller for " + model.getJavaClassName(), e);
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Private generation methods
    // ─────────────────────────────────────────────────────────────────────────

    private void writeController(PrintWriter out, ComponentModel model) {
        // Package and file header
        out.println("package " + model.getGeneratedPackageName() + ";");
        out.println();
        out.println("// ============================================================");
        out.println("// ⚠️  AUTO-GENERATED FILE — DO NOT EDIT MANUALLY");
        out.println("// Generated by JavaLive Annotation Processor");
        out.println("// Source: " + model.getPackageName() + "." + model.getJavaClassName());
        out.println("// Component: " + model.getComponentName());
        out.println("// ============================================================");
        out.println();

        // Imports
        writeImports(out, model);
        out.println();

        // Class declaration
        out.println("@Controller");
        out.println("@SuppressWarnings({\"unchecked\", \"unused\"})");
        out.println("public class " + model.getGeneratedControllerSimpleName() + " {");
        out.println();

        // Autowired dependencies
        writeAutowiredDependencies(out, model);
        out.println();

        // Init handler
        writeInitHandler(out, model);
        out.println();

        // Method handlers
        if (!model.getVueMethods().isEmpty()) {
            out.println("    // ─────────────────────────────────────────────────────────");
            out.println("    // Method Handlers — generated from @VueMethod annotations");
            out.println("    // ─────────────────────────────────────────────────────────");
            out.println();
            for (MethodModel method : model.getVueMethods()) {
                writeMethodHandler(out, model, method);
            }
        }

        // Lifecycle handlers (server-side lifecycle invocations)
        if (!model.getLifecycleMethods().isEmpty()) {
            out.println("    // ─────────────────────────────────────────────────────────");
            out.println("    // Lifecycle Handlers — generated from @VueLifecycle");
            out.println("    // ─────────────────────────────────────────────────────────");
            out.println();
            for (MethodModel lifecycle : model.getLifecycleMethods()) {
                writeLifecycleHandler(out, model, lifecycle);
            }
        }

        out.println("}");
    }

    private void writeImports(PrintWriter out, ComponentModel model) {
        out.println("import org.springframework.beans.factory.annotation.Autowired;");
        out.println("import org.springframework.messaging.handler.annotation.*;");
        out.println("import org.springframework.messaging.simp.SimpMessagingTemplate;");
        out.println("import org.springframework.stereotype.Controller;");
        out.println("import io.javalive.core.session.LiveSessionManager;");
        out.println("import io.javalive.core.state.StateManager;");
        out.println("import io.javalive.core.state.StateDiff;");
        out.println("import io.javalive.core.dispatch.MethodDispatcher;");
        out.println("import io.javalive.core.dispatch.DispatchResult;");
        out.println("import io.javalive.core.dispatch.SecurityGuard;");
        out.println("import io.javalive.core.websocket.ClientMessage;");
        out.println("import io.javalive.core.websocket.ServerMessage;");
        out.println("import " + model.getPackageName() + "." + model.getJavaClassName() + ";");
        out.println("import java.util.Map;");
    }

    private void writeAutowiredDependencies(PrintWriter out, ComponentModel model) {
        out.println("    @Autowired");
        out.println("    private SimpMessagingTemplate messagingTemplate;");
        out.println();
        out.println("    @Autowired");
        out.println("    private LiveSessionManager sessionManager;");
        out.println();
        out.println("    @Autowired");
        out.println("    private StateManager stateManager;");
        out.println();
        out.println("    @Autowired");
        out.println("    private MethodDispatcher methodDispatcher;");
    }

    private void writeInitHandler(PrintWriter out, ComponentModel model) {
        out.println("    // ─────────────────────────────────────────────────────────");
        out.println("    // Init Handler — sends the initial state to the browser");
        out.println("    // ─────────────────────────────────────────────────────────");
        out.println();
        out.println("    @MessageMapping(\"/" + model.getComponentName() + ".init\")");
        out.println("    public void handleInit(");
        out.println("            @Header(\"simpSessionId\") String sessionId) {");
        out.println();
        out.println("        // Create or retrieve the session state for this component");
        out.println("        Map<String, Object> initialState = stateManager.getOrCreate(");
        out.println("            sessionId, \"" + model.getComponentName() + "\");");
        out.println();

        // If there are onMounted lifecycle methods, invoke them first
        boolean hasMounted = model.getLifecycleMethods().stream()
            .anyMatch(m -> "onMounted".equals(m.getLifecycleHook()));
        if (hasMounted) {
            out.println("        // Execute @VueLifecycle(hook=\"onMounted\") methods");
            out.println("        DispatchResult mountResult = methodDispatcher.dispatchLifecycle(");
            out.println("            \"" + model.getPackageName() + "." + model.getJavaClassName() + "\",");
            out.println("            \"onMounted\",");
            out.println("            initialState);");
            out.println("        if (mountResult.getNewState() != null) {");
            out.println("            initialState = mountResult.getNewState();");
            out.println("            stateManager.setState(sessionId,");
            out.println("                \"" + model.getComponentName() + "\", initialState);");
            out.println("        }");
            out.println();
        }

        out.println("        // Send full state to this specific session");
        out.println("        messagingTemplate.convertAndSendToUser(");
        out.println("            sessionId,");
        out.println("            \"" + model.getStateTopic() + "\",");
        out.println("            ServerMessage.fullState(initialState)");
        out.println("        );");
        out.println("    }");
    }

    private void writeMethodHandler(PrintWriter out, ComponentModel model, MethodModel method) {
        String mappingPath = "/" + model.getComponentName() + "." + method.getJavaName();
        boolean hasGlobalState = model.hasGlobalState();

        out.println("    @MessageMapping(\"" + mappingPath + "\")");
        out.println("    public void handle_" + method.getJavaName() + "(");
        out.println("            ClientMessage message,");
        out.println("            @Header(\"simpSessionId\") String sessionId) {");
        out.println();
        out.println("        // Security check: ensure only @VueMethod annotated methods can be called");
        out.println("        SecurityGuard.verify(");
        out.println("            \"" + model.getPackageName() + "." + model.getJavaClassName() + "\",");
        out.println("            \"" + method.getJavaName() + "\");");
        out.println();
        out.println("        // Retrieve current session state");
        out.println("        Map<String, Object> currentState = stateManager.getState(");
        out.println("            sessionId, \"" + model.getComponentName() + "\");");
        out.println();
        out.println("        // Dispatch to the actual Java method");
        out.println("        DispatchResult result = methodDispatcher.dispatch(");
        out.println("            \"" + model.getPackageName() + "." + model.getJavaClassName() + "\",");
        out.println("            \"" + method.getJavaName() + "\",");
        out.println("            currentState,");
        out.println("            message.getArgs());");
        out.println();
        out.println("        if (result.hasError()) {");
        out.println("            // Send error back to the originating session");
        out.println("            messagingTemplate.convertAndSendToUser(");
        out.println("                sessionId,");
        out.println("                \"" + model.getStateTopic() + "\",");
        out.println("                ServerMessage.error(result.getError())");
        out.println("            );");
        out.println("            return;");
        out.println("        }");
        out.println();
        out.println("        // Persist new state");
        out.println("        stateManager.setState(sessionId,");
        out.println("            \"" + model.getComponentName() + "\", result.getNewState());");
        out.println();
        out.println("        // Compute diff and push only changed fields");
        out.println("        StateDiff diff = StateDiff.compute(currentState, result.getNewState());");
        out.println("        if (!diff.isEmpty()) {");
        out.println("            messagingTemplate.convertAndSendToUser(");
        out.println("                sessionId,");
        out.println("                \"" + model.getStateTopic() + "\",");
        out.println("                diff.toServerMessage()");
        out.println("            );");
        out.println("        }");

        // Global state broadcast
        if (hasGlobalState) {
            out.println();
            out.println("        // Broadcast global state changes to ALL connected sessions");
            out.println("        StateDiff globalDiff = StateDiff.computeGlobal(");
            out.println("            currentState, result.getNewState());");
            out.println("        if (!globalDiff.isEmpty()) {");
            out.println("            messagingTemplate.convertAndSend(");
            out.println("                \"" + model.getStateTopic() + ".global\",");
            out.println("                globalDiff.toServerMessage()");
            out.println("            );");
            out.println("        }");
        }

        // Emit event if @VueEmit present
        if (method.isEmitsEvent() && !method.isVoidReturn()) {
            out.println();
            out.println("        // Emit Vue event: '" + method.getEmitEventName() + "'");
            out.println("        messagingTemplate.convertAndSendToUser(");
            out.println("            sessionId,");
            out.println("            \"" + model.getStateTopic() + "\",");
            out.println("            ServerMessage.emit(\"" + method.getEmitEventName() +
                        "\", result.getReturnValue())");
            out.println("        );");
        }

        out.println("    }");
        out.println();
    }

    private void writeLifecycleHandler(PrintWriter out, ComponentModel model, MethodModel lifecycle) {
        // Only generate a handler for onUnmounted (cleanup)
        if (!"onUnmounted".equals(lifecycle.getLifecycleHook())) return;

        out.println("    @MessageMapping(\"/" + model.getComponentName() + ".unmount\")");
        out.println("    public void handleUnmount(");
        out.println("            @Header(\"simpSessionId\") String sessionId) {");
        out.println();
        out.println("        Map<String, Object> currentState = stateManager.getState(");
        out.println("            sessionId, \"" + model.getComponentName() + "\");");
        out.println();
        out.println("        methodDispatcher.dispatchLifecycle(");
        out.println("            \"" + model.getPackageName() + "." + model.getJavaClassName() + "\",");
        out.println("            \"onUnmounted\",");
        out.println("            currentState);");
        out.println("    }");
        out.println();
    }
}
