package io.javalive.processor.generator;

import io.javalive.processor.model.*;

import javax.annotation.processing.ProcessingEnvironment;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Generates a Vue 3 component definition (JavaScript) from a ComponentModel.
 *
 * <p>The generated file is a standard ES Module that exports a Vue component
 * using the Composition API ({@code defineComponent} + {@code setup()}).
 * It is written to {@code static/javalive/components/{component-name}.js}
 * inside the compiled output, making it directly accessible as a static asset.
 *
 * <h3>Generated component structure:</h3>
 * <pre>
 * import { defineComponent, ref, computed, watch, onMounted, ... } from 'vue';
 * import { useLiveState } from '/javalive/runtime.js';
 *
 * export default defineComponent({
 *   name: 'component-name',
 *   props: { ... },        ← from @VueProp
 *   setup(props) {
 *     const { state, dispatch, isConnected, isLoading } = useLiveState(...);
 *     const computedProp = computed(...); ← from @VueComputed
 *     const method = async (...) => { ... }; ← from @VueMethod
 *     watch(() => state.field, ...);       ← from @VueWatch
 *     onMounted(() => { ... });            ← from @VueLifecycle
 *     return { state, isConnected, method, computedProp, ... };
 *   },
 *   template: `...`       ← from @VueTemplate or @VueFile
 * });
 * </pre>
 *
 * @author JavaLive Team
 * @since 1.0.0
 */
public class VueComponentGenerator {

    private final ProcessingEnvironment processingEnv;

    public VueComponentGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    /**
     * Generates the Vue component JavaScript file for the given component.
     *
     * @param model the parsed component model
     */
    public void generate(ComponentModel model) {
        String outputPath = "static/javalive/components/" + model.getComponentName() + ".js";

        try {
            FileObject file = processingEnv.getFiler()
                .createResource(StandardLocation.CLASS_OUTPUT, "", outputPath);

            try (PrintWriter out = new PrintWriter(file.openWriter())) {
                writeVueComponent(out, model);
            }
        } catch (IOException e) {
            throw new RuntimeException(
                "JavaLive: Failed to generate Vue component for " + model.getJavaClassName(), e);
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Private generation methods
    // ─────────────────────────────────────────────────────────────────────────

    private void writeVueComponent(PrintWriter out, ComponentModel model) {
        // File header
        out.println("// ============================================================");
        out.println("// ⚠️  AUTO-GENERATED FILE — DO NOT EDIT MANUALLY");
        out.println("// Generated by JavaLive Annotation Processor");
        out.println("// Source: " + model.getPackageName() + "." + model.getJavaClassName());
        out.println("// ============================================================");
        out.println();

        // Imports
        writeImports(out, model);
        out.println();

        // Component definition
        out.println("export default defineComponent({");
        out.println("  name: '" + model.getComponentName() + "',");
        out.println();

        // Props
        if (model.hasProps()) {
            writePropsDefinition(out, model);
        }

        // Emits declaration
        writeEmitsDeclaration(out, model);

        // Setup function
        out.println("  setup(props, { emit }) {");
        out.println();
        out.println("    // ── JavaLive State Binding ────────────────────────────────");
        writeStateBinding(out, model);
        out.println();

        // Computed properties
        if (!model.getComputedMethods().isEmpty()) {
            out.println("    // ── Computed Properties (@VueComputed) ───────────────────");
            for (MethodModel computed : model.getComputedMethods()) {
                writeComputedProperty(out, model, computed);
            }
            out.println();
        }

        // Methods
        if (!model.getVueMethods().isEmpty()) {
            out.println("    // ── Methods (@VueMethod) ─────────────────────────────────");
            for (MethodModel method : model.getVueMethods()) {
                writeMethod(out, model, method);
            }
            out.println();
        }

        // Watchers
        if (!model.getWatchMethods().isEmpty()) {
            out.println("    // ── Watchers (@VueWatch) ─────────────────────────────────");
            for (MethodModel watcher : model.getWatchMethods()) {
                writeWatcher(out, model, watcher);
            }
            out.println();
        }

        // Lifecycle hooks
        if (!model.getLifecycleMethods().isEmpty()) {
            out.println("    // ── Lifecycle Hooks (@VueLifecycle) ──────────────────────");
            for (MethodModel lifecycle : model.getLifecycleMethods()) {
                writeLifecycleHook(out, model, lifecycle);
            }
            out.println();
        }

        // Return
        writeSetupReturn(out, model);
        out.println("  },");
        out.println();

        // Template
        if (model.hasTemplate()) {
            writeTemplate(out, model);
        }

        out.println("});");
    }

    private void writeImports(PrintWriter out, ComponentModel model) {
        // Determine which Vue APIs are needed
        boolean needsComputed  = !model.getComputedMethods().isEmpty();
        boolean needsWatch     = !model.getWatchMethods().isEmpty();
        boolean hasOnMounted   = model.getLifecycleMethods().stream()
            .anyMatch(m -> "onMounted".equals(m.getLifecycleHook()));
        boolean hasOnUnmounted = model.getLifecycleMethods().stream()
            .anyMatch(m -> "onUnmounted".equals(m.getLifecycleHook()));
        boolean hasOnUpdated   = model.getLifecycleMethods().stream()
            .anyMatch(m -> "onUpdated".equals(m.getLifecycleHook()));

        // Determine whether debounce is needed (from @VueWatch(debounce>0) or @VueMethod(debounce>0))
        boolean needsDebounce = model.getWatchMethods().stream().anyMatch(m -> m.getWatchDebounce() > 0)
            || model.getVueMethods().stream().anyMatch(m -> m.getDebounce() > 0);

        StringBuilder vueImports = new StringBuilder("import { defineComponent");
        if (needsComputed)  vueImports.append(", computed");
        if (needsWatch)     vueImports.append(", watch");
        if (hasOnMounted)   vueImports.append(", onMounted");
        if (hasOnUnmounted) vueImports.append(", onUnmounted");
        if (hasOnUpdated)   vueImports.append(", onUpdated");
        vueImports.append(" } from 'vue';");

        out.println(vueImports);

        // Import debounce from runtime if needed, otherwise just useLiveState
        if (needsDebounce) {
            out.println("import { useLiveState, debounce } from '/javalive/runtime.js';");
        } else {
            out.println("import { useLiveState } from '/javalive/runtime.js';");
        }
    }

    private void writePropsDefinition(PrintWriter out, ComponentModel model) {
        out.println("  props: {");
        for (FieldModel prop : model.getPropFields()) {
            out.println("    " + prop.getJavaName() + ": {");
            out.println("      type: " + prop.getVueType() + ",");
            out.println("      required: " + prop.isRequired() + ",");
            if (!prop.getDefaultValue().equals("null") && !prop.isRequired()) {
                out.println("      default: " + prop.getDefaultValue() + ",");
            }
            if (!prop.getValidator().isEmpty()) {
                out.println("      validator: (value) => { return " + prop.getValidator() + "; },");
            }
            out.println("    },");
        }
        out.println("  },");
        out.println();
    }

    private void writeEmitsDeclaration(PrintWriter out, ComponentModel model) {
        boolean hasEmits = model.getVueMethods().stream().anyMatch(MethodModel::isEmitsEvent);
        if (!hasEmits) return;

        out.println("  emits: [");
        for (MethodModel method : model.getVueMethods()) {
            if (method.isEmitsEvent()) {
                out.println("    '" + method.getEmitEventName() + "',");
            }
        }
        out.println("  ],");
        out.println();
    }

    private void writeStateBinding(PrintWriter out, ComponentModel model) {
        out.println("    const {");
        out.println("      state,");
        out.println("      dispatch,");
        out.println("      isConnected,");
        out.println("      isLoading,");
        out.println("    } = useLiveState('" + model.getComponentName() + "', {");

        // Default values for reactive fields
        for (FieldModel field : model.getReactiveFields()) {
            out.println("      " + field.getJavaName() + ": " + field.getDefaultValue() + ",");
        }

        out.println("    });");
    }

    private void writeComputedProperty(PrintWriter out, ComponentModel model, MethodModel computed) {
        out.println("    const " + computed.getVueName() + " = computed(async () => {");
        out.println("      return dispatch('" + computed.getJavaName() + "', []);");
        out.println("    });");
        out.println();
    }

    private void writeMethod(PrintWriter out, ComponentModel model, MethodModel method) {
        String params = method.getParamNamesJoined();
        int debounce = method.getDebounce();

        if (debounce > 0) {
            // Wrap in debounce
            out.println("    const " + method.getVueName() + " = debounce(async (" + params + ") => {");
        } else {
            out.println("    const " + method.getVueName() + " = async (" + params + ") => {");
        }

        // Confirm dialog
        if (method.isConfirm()) {
            out.println("      if (!confirm('" + method.getConfirmMessage() + "')) return;");
        }

        // Loading state
        if (method.isShowLoading()) {
            out.println("      isLoading.value = true;");
        }

        out.println("      try {");
        String argsLiteral = method.getArgsArrayLiteral();
        out.println("        const result = await dispatch('" + method.getJavaName() + "', " + argsLiteral + ");");

        // Emit event if needed
        if (method.isEmitsEvent()) {
            out.println("        if (result !== undefined) {");
            out.println("          emit('" + method.getEmitEventName() + "', result);");
            out.println("        }");
        }

        out.println("      } catch (error) {");
        out.println("        console.error('JavaLive: Error in " + method.getVueName() + ":', error);");
        out.println("      } finally {");
        if (method.isShowLoading()) {
            out.println("        isLoading.value = false;");
        }
        out.println("      }");

        if (debounce > 0) {
            out.println("    }, " + debounce + ");");
        } else {
            out.println("    };");
        }
        out.println();
    }

    private void writeWatcher(PrintWriter out, ComponentModel model, MethodModel watcher) {
        int watchDebounce = watcher.getWatchDebounce();
        String handlerName = "_watch_" + watcher.getJavaName();

        if (watchDebounce > 0) {
            // Generate debounced watcher handler
            out.println("    const " + handlerName + " = debounce(async (newVal, oldVal) => {");
            out.println("      await dispatch('" + watcher.getJavaName() + "', [newVal, oldVal]);");
            out.println("    }, " + watchDebounce + ");");
        }

        out.println("    watch(");
        out.println("      () => state." + watcher.getWatchTarget() + ",");
        if (watchDebounce > 0) {
            out.println("      " + handlerName + ",");
        } else {
            out.println("      async (newVal, oldVal) => {");
            out.println("        await dispatch('" + watcher.getJavaName() + "', [newVal, oldVal]);");
            out.println("      },");
        }
        out.println("      { deep: " + watcher.isDeep() + ", immediate: " + watcher.isImmediate() + " }");
        out.println("    );");
        out.println();
    }

    private void writeLifecycleHook(PrintWriter out, ComponentModel model, MethodModel lifecycle) {
        String hook = lifecycle.getLifecycleHook();
        out.println("    " + hook + "(async () => {");
        out.println("      await dispatch('" + lifecycle.getJavaName() + "', []);");
        out.println("    });");
        out.println();
    }

    private void writeSetupReturn(PrintWriter out, ComponentModel model) {
        out.println("    return {");
        out.println("      // State & connection");
        out.println("      state,");
        out.println("      isConnected,");
        out.println("      isLoading,");

        if (!model.getVueMethods().isEmpty()) {
            out.println("      // Methods");
            for (MethodModel method : model.getVueMethods()) {
                out.println("      " + method.getVueName() + ",");
            }
        }

        if (!model.getComputedMethods().isEmpty()) {
            out.println("      // Computed");
            for (MethodModel computed : model.getComputedMethods()) {
                out.println("      " + computed.getVueName() + ",");
            }
        }

        out.println("    };");
    }

    private void writeTemplate(PrintWriter out, ComponentModel model) {
        out.println("  template: `");
        out.println(model.getTemplate().getHtmlEscapedForJs());
        out.println("  `,");
        out.println();
    }
}
